FROM quay.io/almalinuxorg/almalinux-bootc:10-kitten

COPY ../../scripts /scripts

RUN /scripts/epel-repo.sh

RUN /scripts/gnome-desktop.sh

RUN /scripts/firewall.sh

RUN /scripts/appimage-compat.sh

RUN /scripts/console-login-helper-messages-remove.sh

RUN /scripts/flathub-repo.sh

RUN /scripts/flatpak-preinstall.sh

RUN /scripts/bootc-update-noapply.sh

RUN /scripts/lint.sh

RUN /scripts/clean.sh
